### ISSUE TITLE
Crahses at startup, container won't run in arm64

### ISSUE THREAD

**Issue by Chillsmeit** [spacebarchat/docker#17]
Hello, I'm using a RaspberryPi5 8Gb with the Raspberry Pi OS Lite image, when I try to startup the server using your docker-compose.yml template for sqlite, the container won't start and just crashes.
Here's the docker-compose.yml (I tried to change it to my settings too but no dice)
```
version: "3.9"
services:
  spacebar:
    image: spacebarchat/server:latest-sqlite-arm64
    ports:
      - "3001:3001"
    volumes:
      - spacebar-database:/exec/persistent/database/
      - spacebar-storage:/exec/persistent/storage
    environment:
      DATABASE: "/exec/persistent/database/database.db"
      STORAGE_PROVIDER: "file"
      STORAGE_LOCATION: "/exec/persistent/storage/"
      PORT: "3001"
volumes:
  spacebar-database:
  spacebar-storage:
  ```
  
  Here are the logs:
[_spacebar-spacebar-1_logs.txt](https://github.com/spacebarchat/docker/files/13652883/_spacebar-spacebar-1_logs.txt)
